### ISSUE TITLE
Failed to resolve: com.segment.retrofit.jsonrpc:jsonrpc:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by ruijun** [segmentio/retrofit-jsonrpc#6]
@f2prateek 
Hello
When I use `retrofit-jsonrpc` in Gradle, it appear this error:

`Failed to resolve: com.segment.retrofit.jsonrpc:jsonrpc:1.0.0-SNAPSHOT`

**Comment by f2prateek** [comment]
You'll need to add the snapshot repo to your buildscript.

**Comment by ruijun** [comment]
@f2prateek Thanks.By the way, can you gvie the Demo for `retrofit-jsonrpc`? I follow the README to write my code,but not success.

**Comment by f2prateek** [comment]
You can see more live samples in https://github.com/segmentio/retrofit-jsonrpc/blob/master/jsonrpc/src/test/java/com/segment/jsonrpc/JsonRPCAdapterTest.java

**Comment by bogdanmunteanu** [comment]
@ruijun Could you explain how you added the snapshot repo ? I am stuck on that . Thanks

**Comment by f2prateek** [comment]
https://github.com/segmentio/analytics-java#snapshots
