### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cyon1c** [segmentio/retrofit-jsonrpc#7]
Hi all! I realize this repository hasn't been maintained in some time, I'd love to fork it, update it, and use it in some projects, however I don't see a license attached to the library.

Is this library meant to be licensed under some open source license, and if not, would it be possible to get permission to fork and use this code?

**Comment by f2prateek** [comment]
Feel free! This should be under the MIT license (https://choosealicense.com/licenses/mit/) like our other repos

**Comment by cyon1c** [comment]
Thank you for the quick response!
